# Generated by Django 5.2.5 on 2025-09-14 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="education",
            options={"ordering": ["-current", "-end_date", "-start_date"]},
        ),
        migrations.AddField(
            model_name="education",
            name="current",
            field=models.BooleanField(default=False),
        ),
    ]
