# Generated by Django 5.0 on 2025-09-21 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_education_options_education_current'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='show',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='show',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='show_headline',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='show_location',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='show_skills',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='show_summary',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='link',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
