# Generated by Django 5.0 on 2025-09-21 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_education_show_experience_show_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='show',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='show',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='show',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
