# Generated by Django 5.2.6 on 2025-11-21 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="account_type",
            field=models.CharField(
                choices=[("JOB_SEEKER", "Job Seeker"), ("RECRUITER", "Recruiter")],
                default="RECRUITER",
                help_text="Controls which features the account can access.",
                max_length=20,
            ),
        ),
    ]
