# Generated by Django 5.2.5 on 2025-09-26 06:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("profiles", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CityCoord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=120)),
                ("state", models.CharField(max_length=120)),
                ("lat", models.FloatField()),
                ("lng", models.FloatField()),
            ],
            options={
                "unique_together": {("city", "state")},
            },
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("company", models.CharField(max_length=200)),
                (
                    "location",
                    models.CharField(
                        blank=True, help_text="City, State or 'Remote'", max_length=200
                    ),
                ),
                (
                    "work_type",
                    models.CharField(
                        choices=[
                            ("REMOTE", "Remote"),
                            ("ON_SITE", "On-site"),
                            ("HYBRID", "Hybrid"),
                        ],
                        default="ON_SITE",
                        max_length=20,
                    ),
                ),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("description", models.TextField()),
                (
                    "requirements",
                    models.TextField(
                        blank=True, help_text="Required qualifications and experience"
                    ),
                ),
                (
                    "salary_min",
                    models.PositiveIntegerField(
                        blank=True, help_text="Minimum salary (USD)", null=True
                    ),
                ),
                (
                    "salary_max",
                    models.PositiveIntegerField(
                        blank=True, help_text="Maximum salary (USD)", null=True
                    ),
                ),
                ("salary_currency", models.CharField(default="USD", max_length=3)),
                (
                    "visa_sponsorship",
                    models.BooleanField(
                        default=False, help_text="Visa sponsorship available"
                    ),
                ),
                (
                    "benefits",
                    models.TextField(blank=True, help_text="Benefits and perks"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("CLOSED", "Closed"),
                            ("DRAFT", "Draft"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "nice_to_have_skills",
                    models.ManyToManyField(
                        blank=True,
                        related_name="jobs_nice_to_have",
                        to="profiles.skill",
                    ),
                ),
                (
                    "posted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posted_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "required_skills",
                    models.ManyToManyField(
                        blank=True, related_name="jobs_required", to="profiles.skill"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="JobApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("APPLIED", "Applied"),
                            ("REVIEWING", "Under Review"),
                            ("INTERVIEW", "Interview"),
                            ("OFFER", "Offer Extended"),
                            ("ACCEPTED", "Offer Accepted"),
                            ("REJECTED", "Not Selected"),
                            ("WITHDRAWN", "Withdrawn"),
                        ],
                        default="APPLIED",
                        max_length=20,
                    ),
                ),
                (
                    "cover_letter",
                    models.TextField(
                        blank=True, help_text="Optional personalized message"
                    ),
                ),
                ("applied_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status_notes",
                    models.TextField(
                        blank=True, help_text="Internal notes about status changes"
                    ),
                ),
                ("last_status_change", models.DateTimeField(auto_now=True)),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="jobs.job",
                    ),
                ),
            ],
            options={
                "ordering": ["-applied_at"],
            },
        ),
        migrations.CreateModel(
            name="ApplicationStatusChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "old_status",
                    models.CharField(
                        choices=[
                            ("APPLIED", "Applied"),
                            ("REVIEWING", "Under Review"),
                            ("INTERVIEW", "Interview"),
                            ("OFFER", "Offer Extended"),
                            ("ACCEPTED", "Offer Accepted"),
                            ("REJECTED", "Not Selected"),
                            ("WITHDRAWN", "Withdrawn"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        choices=[
                            ("APPLIED", "Applied"),
                            ("REVIEWING", "Under Review"),
                            ("INTERVIEW", "Interview"),
                            ("OFFER", "Offer Extended"),
                            ("ACCEPTED", "Offer Accepted"),
                            ("REJECTED", "Not Selected"),
                            ("WITHDRAWN", "Withdrawn"),
                        ],
                        max_length=20,
                    ),
                ),
                ("changed_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("notes", models.TextField(blank=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_changes_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_changes",
                        to="jobs.jobapplication",
                    ),
                ),
            ],
            options={
                "ordering": ["-changed_at"],
            },
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["status", "created_at"], name="jobs_job_status_277b31_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["work_type"], name="jobs_job_work_ty_4ebff2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(fields=["location"], name="jobs_job_locatio_8b2f8c_idx"),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["salary_min", "salary_max"], name="jobs_job_salary__2892b4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobapplication",
            index=models.Index(
                fields=["applicant", "status"], name="jobs_jobapp_applica_089491_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobapplication",
            index=models.Index(
                fields=["job", "status"], name="jobs_jobapp_job_id_08192b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobapplication",
            index=models.Index(
                fields=["status", "updated_at"], name="jobs_jobapp_status_6d8fad_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="jobapplication",
            unique_together={("job", "applicant")},
        ),
    ]
