# Generated by Django 5.0 on 2025-09-25 23:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationStatusChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(choices=[('APPLIED', 'Applied'), ('REVIEWING', 'Under Review'), ('INTERVIEW', 'Interview'), ('OFFER', 'Offer Extended'), ('ACCEPTED', 'Offer Accepted'), ('REJECTED', 'Not Selected'), ('WITHDRAWN', 'Withdrawn')], max_length=20)),
                ('new_status', models.CharField(choices=[('APPLIED', 'Applied'), ('REVIEWING', 'Under Review'), ('INTERVIEW', 'Interview'), ('OFFER', 'Offer Extended'), ('ACCEPTED', 'Offer Accepted'), ('REJECTED', 'Not Selected'), ('WITHDRAWN', 'Withdrawn')], max_length=20)),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='last_status_change',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='status_notes',
            field=models.TextField(blank=True, help_text='Internal notes about status changes'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='cover_letter',
            field=models.TextField(blank=True, help_text='Optional personalized message'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('APPLIED', 'Applied'), ('REVIEWING', 'Under Review'), ('INTERVIEW', 'Interview'), ('OFFER', 'Offer Extended'), ('ACCEPTED', 'Offer Accepted'), ('REJECTED', 'Not Selected'), ('WITHDRAWN', 'Withdrawn')], default='APPLIED', max_length=20),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['applicant', 'status'], name='jobs_jobapp_applica_089491_idx'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['job', 'status'], name='jobs_jobapp_job_id_08192b_idx'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['status', 'updated_at'], name='jobs_jobapp_status_6d8fad_idx'),
        ),
        migrations.AddField(
            model_name='applicationstatuschange',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_changes', to='jobs.jobapplication'),
        ),
        migrations.AddField(
            model_name='applicationstatuschange',
            name='changed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_changes_made', to=settings.AUTH_USER_MODEL),
        ),
    ]
