# Generated by Django 5.0 on 2025-10-22 03:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedCandidateSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name for this saved search (e.g., 'Senior Python Developers in NYC')", max_length=200)),
                ('skills', models.TextField(blank=True, help_text='Comma-separated skill names')),
                ('location', models.CharField(blank=True, max_length=200)),
                ('experience_min', models.IntegerField(blank=True, null=True)),
                ('experience_max', models.IntegerField(blank=True, null=True)),
                ('notify_on_new_matches', models.BooleanField(default=True, help_text='Send notification when new candidates match this search')),
                ('last_notified', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_candidate_searches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saved Candidate Search',
                'verbose_name_plural': 'Saved Candidate Searches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SearchNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('candidates_count', models.IntegerField(default=0)),
                ('new_candidates', models.ManyToManyField(blank=True, related_name='search_notifications', to=settings.AUTH_USER_MODEL)),
                ('saved_search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='jobs.savedcandidatesearch')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
    ]
