# Generated by Django 5.0 on 2025-10-22 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_savedcandidatesearch_searchnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchnotification',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='searchnotification',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
