# Generated by Django 5.0 on 2025-09-26 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_latitude_job_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityCoord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=120)),
                ('state', models.CharField(max_length=120)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
            ],
            options={
                'unique_together': {('city', 'state')},
            },
        ),
    ]
