# Generated by Django 5.2.6 on 2025-10-23 21:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0003_searchnotification_is_read_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="savedcandidatesearch",
            constraint=models.UniqueConstraint(
                fields=("recruiter", "name"),
                name="uniq_saved_candidate_search_name_per_recruiter",
            ),
        ),
    ]
