# Generated by Django 5.0 on 2025-11-09 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_savedcandidatesearch_uniq_saved_candidate_search_name_per_recruiter'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='moderated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='moderated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='job',
            name='moderation_notes',
            field=models.TextField(blank=True, help_text='Notes from administrator about removal or other actions'),
        ),
        migrations.AlterField(
            model_name='applicationstatuschange',
            name='new_status',
            field=models.CharField(choices=[('APPLIED', 'Applied'), ('REVIEWING', 'Under Review'), ('INTERVIEW', 'Interview'), ('OFFER', 'Offer'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Not Selected')], max_length=20),
        ),
        migrations.AlterField(
            model_name='applicationstatuschange',
            name='old_status',
            field=models.CharField(choices=[('APPLIED', 'Applied'), ('REVIEWING', 'Under Review'), ('INTERVIEW', 'Interview'), ('OFFER', 'Offer'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Not Selected')], max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('CLOSED', 'Closed'), ('DRAFT', 'Draft'), ('REMOVED', 'Removed by Admin')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('APPLIED', 'Applied'), ('REVIEWING', 'Under Review'), ('INTERVIEW', 'Interview'), ('OFFER', 'Offer'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Not Selected')], default='APPLIED', max_length=20),
        ),
    ]
